services:
  pjl2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "localhost:28122:8080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"